### ISSUE TITLE
Makefile: problème de dépendance sur debug

### ISSUE THREAD

**Issue by dbaelde** [severus21/ide_cachan#6]
Après un `make debug`, réussi ou pas, le prochain `make debug` ne fait jamais rien:
```
$ make
make: Nothing to be done for 'default'.
$ make debug
make: 'debug' is up to date.
```
C'est gênant en cas d'échec, si l'on souhaite refaire une tentative.

La raison est que le répertoire `debug` est créé par ocamlbuild automatiquement et, selon la sémantique de make, puisque la cible `debug` n'a pas de dépendance, elle n'est exécutée que si `debug` n'existe pas.

Deux solutions: éviter que la cible et le répertoire de build aient le même nom, ou bien spécifier que la cible `debug` est `PHONY` (à exécuter sans condition, ce qui est légitime puisque ocamlbuild est en charge des dépendances).

**Comment by severus21** [comment]
Maintenant debug est PHONY
