### ISSUE TITLE
Quels imports sont possibles?

### ISSUE THREAD

**Issue by dbaelde** [severus21/ide_cachan#7]
Dans l'IDE, quand je sélectionne import, j'obtiens un navigateur de fichier. Je ne peux ni y sélectionner des fichiers OCaml, ni des répertoires. Est-ce sensé fonctionner, et comment? Plus généralement, il serait bienvenu de mettre au point une petite documentation utilisateur indiquant comment compiler le projet et l'utiliser.

**Comment by Stenodyon** [comment]
En ce qui concerne l'import, il faut sélectionner un dossier. Cependant, le bouton "Open" ne fonctionne pas et je n'arrive pas à déterminer comment régler ce problème; la documentation lablgtk est inexistante là-dessus.
